version: '3.8'

services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8002:8000
    env_file:
      - .env
    depends_on:
      - redis
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  worker:
      build: ./src
      command: celery -A app.worker.celery worker --loglevel=info --pool=eventlet
      volumes:
        - ./src/:/usr/src/app/
      env_file:
      - .env
      depends_on:
        - web
        - redis

  beat:
      build: ./src
      command: celery -A app.worker.celery beat --loglevel=info
      volumes:
        - ./src/:/usr/src/app/
      env_file:
      - .env
      depends_on:
        - web
        - redis

  redis:
    image: redis:7

volumes:
  postgres_data: