version: '3.8'

services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=${BROKER_URL}
      - CELERY_RESULT_BACKEND=${BROKER_URL}
    depends_on:
      - redis
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  worker:
      build: ./src
      command: celery -A worker.celery worker --loglevel=info
      volumes:
        - ./src/:/usr/src/app/
      environment:
        - CELERY_BROKER_URL=${BROKER_URL}
        - CELERY_RESULT_BACKEND=${BROKER_URL}
      depends_on:
        - web
        - redis

  redis:
    image: redis:7

volumes:
  postgres_data: